name: 'Static UEFI Binary Analysis'
description: 'Static Analysis for UEFI binaries'

inputs:
  path:
    description: 'Path to the target UEFI binary'
    required: true
  report_path:
    description: 'Path to the report'
    required: true

outputs:
  report:
    description: 'Static analysis report in XML JUnit format'

runs:
  using: 'docker'
  image: 'Dockerfile'
