name: CI

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: CI Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: retrage/efiseek-action@main
        with:
          path: tests/binaries/DoubleGetVariable.efi
          report_path: analysis.xml

      - uses: EnricoMi/publish-unit-test-result-action@v2.17.1
        with:
          files: analysis.xml